//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\*.xsd
namespace Mets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IFilecoreChecksumtype", Namespace="http://www.loc.gov/METS/", AnonymousType=true)]
    public enum IFilecoreChecksumtype
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("Adler-32")]
        ADLER32,
        
        [System.Xml.Serialization.XmlEnumAttribute("CRC32")]
        CRC32,
        
        [System.Xml.Serialization.XmlEnumAttribute("HAVAL")]
        HAVAL,
        
        [System.Xml.Serialization.XmlEnumAttribute("MD5")]
        MD5,
        
        [System.Xml.Serialization.XmlEnumAttribute("MNP")]
        MNP,
        
        [System.Xml.Serialization.XmlEnumAttribute("SHA-1")]
        SHA1,
        
        [System.Xml.Serialization.XmlEnumAttribute("SHA-256")]
        SHA256,
        
        [System.Xml.Serialization.XmlEnumAttribute("SHA-384")]
        SHA384,
        
        [System.Xml.Serialization.XmlEnumAttribute("SHA-512")]
        SHA512,
        
        [System.Xml.Serialization.XmlEnumAttribute("TIGER")]
        TIGER,
        
        [System.Xml.Serialization.XmlEnumAttribute("WHIRLPOOL")]
        WHIRLPOOL,
    }
}
