//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\mets.xsd
namespace Mets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IFilecoreChecksumtype", Namespace="http://www.loc.gov/METS/", AnonymousType=true)]
    public enum IFilecoreChecksumtype
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("Adler-32")]
        Adler32,
        
        [System.Xml.Serialization.XmlEnumAttribute("CRC32")]
        Crc32,
        
        [System.Xml.Serialization.XmlEnumAttribute("HAVAL")]
        Haval,
        
        [System.Xml.Serialization.XmlEnumAttribute("MD5")]
        Md5,
        
        [System.Xml.Serialization.XmlEnumAttribute("MNP")]
        Mnp,
        
        [System.Xml.Serialization.XmlEnumAttribute("SHA-1")]
        Sha1,
        
        [System.Xml.Serialization.XmlEnumAttribute("SHA-256")]
        Sha256,
        
        [System.Xml.Serialization.XmlEnumAttribute("SHA-384")]
        Sha384,
        
        [System.Xml.Serialization.XmlEnumAttribute("SHA-512")]
        Sha512,
        
        [System.Xml.Serialization.XmlEnumAttribute("TIGER")]
        Tiger,
        
        [System.Xml.Serialization.XmlEnumAttribute("WHIRLPOOL")]
        Whirlpool,
    }
}
