//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\mets.xsd
namespace Mets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ILocationLoctype", Namespace="http://www.loc.gov/METS/", AnonymousType=true)]
    public enum ILocationLoctype
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("ARK")]
        Ark,
        
        [System.Xml.Serialization.XmlEnumAttribute("URN")]
        Urn,
        
        [System.Xml.Serialization.XmlEnumAttribute("URL")]
        Url,
        
        [System.Xml.Serialization.XmlEnumAttribute("PURL")]
        Purl,
        
        [System.Xml.Serialization.XmlEnumAttribute("HANDLE")]
        Handle,
        
        [System.Xml.Serialization.XmlEnumAttribute("DOI")]
        Doi,
        
        [System.Xml.Serialization.XmlEnumAttribute("OTHER")]
        Other,
    }
}
