//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\mets.xsd
namespace Mets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IMetadataMdtype", Namespace="http://www.loc.gov/METS/", AnonymousType=true)]
    public enum IMetadataMdtype
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("MARC")]
        Marc,
        
        [System.Xml.Serialization.XmlEnumAttribute("MODS")]
        Mods,
        
        [System.Xml.Serialization.XmlEnumAttribute("EAD")]
        Ead,
        
        [System.Xml.Serialization.XmlEnumAttribute("DC")]
        Dc,
        
        [System.Xml.Serialization.XmlEnumAttribute("NISOIMG")]
        Nisoimg,
        
        [System.Xml.Serialization.XmlEnumAttribute("LC-AV")]
        LcAv,
        
        [System.Xml.Serialization.XmlEnumAttribute("VRA")]
        Vra,
        
        [System.Xml.Serialization.XmlEnumAttribute("TEIHDR")]
        Teihdr,
        
        [System.Xml.Serialization.XmlEnumAttribute("DDI")]
        Ddi,
        
        [System.Xml.Serialization.XmlEnumAttribute("FGDC")]
        Fgdc,
        
        [System.Xml.Serialization.XmlEnumAttribute("LOM")]
        Lom,
        
        [System.Xml.Serialization.XmlEnumAttribute("PREMIS")]
        Premis,
        
        [System.Xml.Serialization.XmlEnumAttribute("PREMIS:OBJECT")]
        PremisObject,
        
        [System.Xml.Serialization.XmlEnumAttribute("PREMIS:AGENT")]
        PremisAgent,
        
        [System.Xml.Serialization.XmlEnumAttribute("PREMIS:RIGHTS")]
        PremisRights,
        
        [System.Xml.Serialization.XmlEnumAttribute("PREMIS:EVENT")]
        PremisEvent,
        
        [System.Xml.Serialization.XmlEnumAttribute("TEXTMD")]
        Textmd,
        
        [System.Xml.Serialization.XmlEnumAttribute("METSRIGHTS")]
        Metsrights,
        
        [System.Xml.Serialization.XmlEnumAttribute("ISO 19115:2003 NAP")]
        Iso191152003Nap,
        
        [System.Xml.Serialization.XmlEnumAttribute("EAC-CPF")]
        EacCpf,
        
        [System.Xml.Serialization.XmlEnumAttribute("LIDO")]
        Lido,
        
        [System.Xml.Serialization.XmlEnumAttribute("OTHER")]
        Other,
    }
}
