//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\*.xsd
namespace Xml.Mets.CsipExtensionMets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NOTETYPE", Namespace="https://DILCIS.eu/XML/METS/CSIPExtensionMETS", AnonymousType=true)]
    public enum Notetype
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("SOFTWARE VERSION")]
        SOFTWARE_VERSION,
        
        [System.Xml.Serialization.XmlEnumAttribute("IDENTIFICATIONCODE")]
        IDENTIFICATIONCODE,
    }
}
