//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\*.xsd
namespace Xlink
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("actuate", Namespace="http://www.w3.org/1999/xlink", AnonymousType=true)]
    public enum Actuate
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("onLoad")]
        OnLoad,
        
        [System.Xml.Serialization.XmlEnumAttribute("onRequest")]
        OnRequest,
        
        [System.Xml.Serialization.XmlEnumAttribute("other")]
        Other,
        
        [System.Xml.Serialization.XmlEnumAttribute("none")]
        None,
    }
}
