//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\*.xsd
namespace Xml.Mets.CsipExtensionMets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CONTENTINFORMATIONTYPE", Namespace="https://DILCIS.eu/XML/METS/CSIPExtensionMETS", AnonymousType=true)]
    public enum Contentinformationtype
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("ERMS")]
        ERMS,
        
        [System.Xml.Serialization.XmlEnumAttribute("SIARD1")]
        SIARD1,
        
        [System.Xml.Serialization.XmlEnumAttribute("SIARD2")]
        SIARD2,
        
        [System.Xml.Serialization.XmlEnumAttribute("SIARDDK")]
        SIARDDK,
        
        [System.Xml.Serialization.XmlEnumAttribute("GeoData")]
        GEODATA,
        
        [System.Xml.Serialization.XmlEnumAttribute("citcarchival_v1_0")]
        CITCARCHIVALV10,
        
        [System.Xml.Serialization.XmlEnumAttribute("citsarchival_v1_0")]
        CITSARCHIVALV10,
        
        [System.Xml.Serialization.XmlEnumAttribute("csarchival_v1_0")]
        CSARCHIVALV10,
        
        [System.Xml.Serialization.XmlEnumAttribute("citspremis_v1_0")]
        CITSPREMISV10,
        
        [System.Xml.Serialization.XmlEnumAttribute("cspremis_v1_0")]
        CSPREMISV10,
        
        [System.Xml.Serialization.XmlEnumAttribute("citserms_v2_1")]
        CITSERMSV21,
        
        [System.Xml.Serialization.XmlEnumAttribute("citserms_v3_0")]
        CITSERMSV30,
        
        [System.Xml.Serialization.XmlEnumAttribute("citsehpj_v1_0")]
        CITSEHPJV10,
        
        [System.Xml.Serialization.XmlEnumAttribute("citsehpj_v2_0")]
        CITSEHPJV20,
        
        [System.Xml.Serialization.XmlEnumAttribute("citsehcr_v1_0")]
        CITSEHCRV10,
        
        [System.Xml.Serialization.XmlEnumAttribute("citssiard_v1_0")]
        CITSSIARDV10,
        
        [System.Xml.Serialization.XmlEnumAttribute("citsgeospatial_v3_0")]
        CITSGEOSPATIALV30,
        
        [System.Xml.Serialization.XmlEnumAttribute("MIXED")]
        MIXED,
        
        [System.Xml.Serialization.XmlEnumAttribute("OTHER")]
        OTHER,
    }
}
