//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\*.xsd
namespace Xml.Mets.CsipExtensionMets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OAISPACKAGETYPE", Namespace="https://DILCIS.eu/XML/METS/CSIPExtensionMETS", AnonymousType=true)]
    public enum Oaispackagetype
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("SIP")]
        SIP,
        
        [System.Xml.Serialization.XmlEnumAttribute("AIP")]
        AIP,
        
        [System.Xml.Serialization.XmlEnumAttribute("DIP")]
        DIP,
        
        [System.Xml.Serialization.XmlEnumAttribute("AIU")]
        AIU,
        
        [System.Xml.Serialization.XmlEnumAttribute("AIC")]
        AIC,
    }
}
