//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\*.xsd
namespace Mets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AreaTypeExttype", Namespace="http://www.loc.gov/METS/", AnonymousType=true)]
    public enum AreaTypeExttype
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("BYTE")]
        BYTE,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMIL")]
        SMIL,
        
        [System.Xml.Serialization.XmlEnumAttribute("MIDI")]
        MIDI,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-25")]
        SMPTE25,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-24")]
        SMPTE24,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-DF30")]
        SMPTEDF30,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-NDF30")]
        SMPTENDF30,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-DF29.97")]
        SMPTEDF2997,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-NDF29.97")]
        SMPTENDF2997,
        
        [System.Xml.Serialization.XmlEnumAttribute("TIME")]
        TIME,
        
        [System.Xml.Serialization.XmlEnumAttribute("TCF")]
        TCF,
    }
}
