//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\*.xsd
namespace Mets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    public partial interface ILocation
    {
        
        /// <summary>
        /// <para xml:lang="en">LOCTYPE (string/R): Specifies the locator type used in the xlink:href attribute. Valid values for LOCTYPE are: 
        ///					ARK
        ///					URN
        ///					URL
        ///					PURL
        ///					HANDLE
        ///					DOI
        ///					OTHER</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("LOCTYPE (string/R): Specifies the locator type used in the xlink:href attribute. " +
            "Valid values for LOCTYPE are: ARK URN URL PURL HANDLE DOI OTHER")]
        ILocationLoctype Loctype
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para xml:lang="en">OTHERLOCTYPE (string/O): Specifies the locator type when the value OTHER is used in the LOCTYPE attribute. Although optional, it is strongly recommended when OTHER is used.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("OTHERLOCTYPE (string/O): Specifies the locator type when the value OTHER is used " +
            "in the LOCTYPE attribute. Although optional, it is strongly recommended when OTH" +
            "ER is used.")]
        string Otherloctype
        {
            get;
            set;
        }
    }
}
