//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\*.xsd
namespace Mets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IMetadataMdtype", Namespace="http://www.loc.gov/METS/", AnonymousType=true)]
    public enum IMetadataMdtype
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("MARC")]
        MARC,
        
        [System.Xml.Serialization.XmlEnumAttribute("MODS")]
        MODS,
        
        [System.Xml.Serialization.XmlEnumAttribute("EAD")]
        EAD,
        
        [System.Xml.Serialization.XmlEnumAttribute("DC")]
        DC,
        
        [System.Xml.Serialization.XmlEnumAttribute("NISOIMG")]
        NISOIMG,
        
        [System.Xml.Serialization.XmlEnumAttribute("LC-AV")]
        LCAV,
        
        [System.Xml.Serialization.XmlEnumAttribute("VRA")]
        VRA,
        
        [System.Xml.Serialization.XmlEnumAttribute("TEIHDR")]
        TEIHDR,
        
        [System.Xml.Serialization.XmlEnumAttribute("DDI")]
        DDI,
        
        [System.Xml.Serialization.XmlEnumAttribute("FGDC")]
        FGDC,
        
        [System.Xml.Serialization.XmlEnumAttribute("LOM")]
        LOM,
        
        [System.Xml.Serialization.XmlEnumAttribute("PREMIS")]
        PREMIS,
        
        [System.Xml.Serialization.XmlEnumAttribute("PREMIS:OBJECT")]
        PREMISOBJECT,
        
        [System.Xml.Serialization.XmlEnumAttribute("PREMIS:AGENT")]
        PREMISAGENT,
        
        [System.Xml.Serialization.XmlEnumAttribute("PREMIS:RIGHTS")]
        PREMISRIGHTS,
        
        [System.Xml.Serialization.XmlEnumAttribute("PREMIS:EVENT")]
        PREMISEVENT,
        
        [System.Xml.Serialization.XmlEnumAttribute("TEXTMD")]
        TEXTMD,
        
        [System.Xml.Serialization.XmlEnumAttribute("METSRIGHTS")]
        METSRIGHTS,
        
        [System.Xml.Serialization.XmlEnumAttribute("ISO 19115:2003 NAP")]
        ISO191152003NAP,
        
        [System.Xml.Serialization.XmlEnumAttribute("EAC-CPF")]
        EACCPF,
        
        [System.Xml.Serialization.XmlEnumAttribute("LIDO")]
        LIDO,
        
        [System.Xml.Serialization.XmlEnumAttribute("OTHER")]
        OTHER,
    }
}
