//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\mets.xsd
namespace Mets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AreaTypeExttype", Namespace="http://www.loc.gov/METS/", AnonymousType=true)]
    public enum AreaTypeExttype
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("BYTE")]
        Byte,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMIL")]
        Smil,
        
        [System.Xml.Serialization.XmlEnumAttribute("MIDI")]
        Midi,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-25")]
        Smpte25,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-24")]
        Smpte24,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-DF30")]
        SmpteDf30,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-NDF30")]
        SmpteNdf30,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-DF29.97")]
        SmpteDf2997,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMPTE-NDF29.97")]
        SmpteNdf2997,
        
        [System.Xml.Serialization.XmlEnumAttribute("TIME")]
        Time,
        
        [System.Xml.Serialization.XmlEnumAttribute("TCF")]
        Tcf,
    }
}
