//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\*.xsd
namespace Mets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MetsTypeMetsHdrAgentRole", Namespace="http://www.loc.gov/METS/", AnonymousType=true)]
    public enum MetsTypeMetsHdrAgentRole
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("CREATOR")]
        CREATOR,
        
        [System.Xml.Serialization.XmlEnumAttribute("EDITOR")]
        EDITOR,
        
        [System.Xml.Serialization.XmlEnumAttribute("ARCHIVIST")]
        ARCHIVIST,
        
        [System.Xml.Serialization.XmlEnumAttribute("PRESERVATION")]
        PRESERVATION,
        
        [System.Xml.Serialization.XmlEnumAttribute("DISSEMINATOR")]
        DISSEMINATOR,
        
        [System.Xml.Serialization.XmlEnumAttribute("CUSTODIAN")]
        CUSTODIAN,
        
        [System.Xml.Serialization.XmlEnumAttribute("IPOWNER")]
        IPOWNER,
        
        [System.Xml.Serialization.XmlEnumAttribute("OTHER")]
        OTHER,
    }
}
