//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\mets.xsd
namespace Mets
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MetsTypeMetsHdrAgentRole", Namespace="http://www.loc.gov/METS/", AnonymousType=true)]
    public enum MetsTypeMetsHdrAgentRole
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("CREATOR")]
        Creator,
        
        [System.Xml.Serialization.XmlEnumAttribute("EDITOR")]
        Editor,
        
        [System.Xml.Serialization.XmlEnumAttribute("ARCHIVIST")]
        Archivist,
        
        [System.Xml.Serialization.XmlEnumAttribute("PRESERVATION")]
        Preservation,
        
        [System.Xml.Serialization.XmlEnumAttribute("DISSEMINATOR")]
        Disseminator,
        
        [System.Xml.Serialization.XmlEnumAttribute("CUSTODIAN")]
        Custodian,
        
        [System.Xml.Serialization.XmlEnumAttribute("IPOWNER")]
        Ipowner,
        
        [System.Xml.Serialization.XmlEnumAttribute("OTHER")]
        Other,
    }
}
